name: CI workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build Job (CI Lab)
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt
      - name: Format code with Black
        run: black src
      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics 
      - name: Security check with Bandit
        run: bandit -r src
      - name: Run unit tests with pytest
        run: pytest -v --tb=short --color=yes --cov=src --cov-report=term-missing --html=pytest_report.html 
      - name: Upload pytest report
        uses: actions/upload-artifact@v2
        with:
          name: pytest-report
          path: pytest_report.html
